# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    identifier: research
    url: research/
    weight: 10

  - name: Advanced Semiconductor Packaging
    parent: research
    url: research/advanced-semiconductor-packaging/
    weight: 10

  - name: MEMS
    parent: research
    url: research/mems/
    weight: 20

  - name: Publications
    url: publications
    weight: 30

  - name: People
    url: people
    weight: 40
    
  - name: Openings 
    url: openings
    weight: 50

  - name: Contact
    url: contact
    weight: 60
